"""Central permission catalog for all ERP modules."""

PERMISSIONS: dict[str, str] = {
    "org:read": "View organisation structure (group/institution/campus/department)",
    "org:write": "Create/update organisation units",
    "config:read": "View global configuration",
    "config:write": "Update global configuration",
    "user:read": "View user accounts",
    "user:write": "Create/update user accounts",
    "user:lock": "Lock/unlock user accounts",
    "role:read": "View roles and permissions",
    "role:write": "Create/update roles and assign permissions",
    "audit:read": "View audit and login history",
    "vendor:read": "View vendor master and empanelment details",
    "vendor:write": "Create/update vendors, blacklist/reinstate",
    "catalog:read": "View item catalog",
    "catalog:write": "Create/update catalog items",
    "indent:read": "View department indents/requisitions",
    "indent:write": "Create/submit indents",
    "indent:approve": "Approve or reject submitted indents",
    "quotation:read": "View RFQs, vendor quotes and comparative statements",
    "quotation:write": "Create RFQs and record vendor quotes",
    "quotation:award": "Award a quotation to a vendor (comparative committee decision)",
    "po:read": "View purchase orders",
    "po:write": "Create/amend purchase orders",
    "po:approve": "Approve/issue and cancel purchase orders",
    "grn:read": "View goods receipt notes",
    "grn:write": "Record goods receipt against a purchase order",
    "bill:read": "View vendor purchase bills",
    "bill:write": "Book vendor purchase bills",
    "bill:approve": "Approve vendor purchase bills for payment",
    "stores:read": "View stores, stock balances and stock transactions",
    "stores:write": "Create/update stores and post opening / GRN receipt stock",
    "stores:issue": "Issue, return and transfer stock between stores",
    "stores:adjust": "Post stock adjustments and write-offs",
    "assets:read": "View fixed asset register and movements",
    "assets:write": "Create/update assets",
    "assets:transfer": "Transfer asset custodian/location",
    "assets:dispose": "Dispose or write-off assets",
    "hr:read": "View employee master and designations",
    "hr:write": "Create/update employees and designations",
    "hr:sensitive": "View unmasked PAN, bank and identity fields",
    "attendance:read": "View attendance records and shifts",
    "attendance:write": "Record and correct attendance",
    "leave:read": "View leave types, balances and applications",
    "leave:write": "Apply for leave and submit applications",
    "leave:approve": "Approve or reject leave applications",
    "payroll:read": "View payroll runs, structures and payslips",
    "payroll:write": "Create and process payroll runs",
    "payroll:approve": "Approve and lock payroll runs",
    "payroll:sensitive": "View full salary details without masking",
    "accounts:read": "View chart of accounts, vouchers and statements",
    "accounts:write": "Create and validate vouchers",
    "accounts:approve": "Approve vouchers",
    "accounts:post": "Post and reverse vouchers",
    "budget:read": "View budgets and commitments",
    "budget:write": "Create and amend budgets",
    "reports:read": "View reports centre and analytics",
    "reports:export": "Export reports to Excel/PDF",
}

SUPER_ADMIN_CODE = "*"


def is_valid_permission(code: str) -> bool:
    return code == SUPER_ADMIN_CODE or code in PERMISSIONS
